import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface LayoutProps {
	children: React.ReactNode;
}

const RootLayout: React.FC<LayoutProps> = ({ children }) => {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
